name: release

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Install Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install Nodejs    
        uses: pnpm/action-setup@v2
        with:
          version: ^7.25.0
      - name: Get Dependencies
        run: pnpm i
      - name: Build
        run: pnpm build
      - name: Deploy To Server
        uses: wlixcc/SFTP-Deploy-Action@v1.2 # 使用 SFTP 协议上传到腾讯云
        with:
          username: 'root'
          server: ${{ secrets.TENCENT_SERVER_IP }}
          port: '22'
          ssh_private_key: ${{ secrets.TENCENT_PRIMARY_SSH_KEY }}
          local_path: './dist/*'
          remote_path: '/var/www/'
          sftp_only: true
          sftpArgs: "-o ConnectTimeout=5"